### ISSUE TITLE
promtail logs are not being updated because Docker containers don't update mounted files

### ISSUE THREAD

**Issue by fguillen** [Rovel/profana#14]
I am using your repo as inspiration to configure promtail using Docker in my project. Appologice if this issue is not happening on your setup.

when I start the promtail image with:

    docker-compose up promtail

I see the logs are being detected:

```
promtail_1  | level=info ts=2024-05-14T19:39:32.980862331Z caller=tailer.go:147 component=tailer msg="tail routine: started" path=/var/log/rails/development.log
```

And they are digested by Loki and presented in Grafana.

But new logs are not being detected. 

If I `bash` into the `promtail` image I see the `/var/log/rails/*.log` files are frozen and they are not being updated with my locals `/railsapp/logs/*.log`. 

This looks to be a limitation with Docker containers: https://stackoverflow.com/questions/52897000/docker-files-from-volume-not-updated-in-target

Did you manage to make this work?

Thanks for your support and your work.

**Comment by fguillen** [comment]
More details here: https://stackoverflow.com/questions/78480575/rails-log-files-in-volume-are-not-being-updated-inside-docker-image

**Comment by fguillen** [comment]
It works when the rails app is also running in a Docker container... mysterious from Docker :)

**Comment by Rovel** [comment]
Hi, thanks for the info, and glad this project worked as an inspiration to you! :)

No I did not notice any of these issues since I ran all in containers, Promtail needs to be in tandem with the container they are logging so Im not sure why is not working when Rails is local, probably it has to do with the container not being accessible by localhost due to port exposure or r/w issues with volumes. I ran in other projects with issues related to folder ownership when docker and local write in the same folder with different root names and permissions.
if you need any further help please let me know.
